# Front Matter global settings
# ----------------------------

# Default title
title: "0xNixxy Tech Tips"

# Default description
description: "Tech Tips for the busy folk"


# Build settings
# --------------

# Use Primer Dark theme tagged to commit hash
remote_theme: 0xNixxy/primer-dark@355a492

# Plugins required for Primer Dark
plugins:
  - jekyll-remote-theme